// Sample data - in a real app, this would come from an API
export const mangaData = [
  {
    id: "1",
    title: "Solo Leveling",
    current_chapter: "178",
    status: "ENDED",
    img_path: "/placeholder.svg?height=400&width=300",
    rating: 9.2,
    updatedAt: "2024-01-15",
    source: "https://asuracomic.net/series/solo-leveling-12345/chapter/178",
  },
  {
    id: "2",
    title: "One Piece",
    current_chapter: "1113",
    status: "ONGOING",
    img_path: "/placeholder.svg?height=400&width=300",
    rating: 9.5,
    updatedAt: "2024-01-14",
    source: "https://onepiece.fandom.com/wiki/Chapter_1113",
  },
  {
    id: "3",
    title: "Attack on Titan",
    current_chapter: "139",
    status: "ENDED",
    img_path: "/placeholder.svg?height=400&width=300",
    rating: 9.0,
    updatedAt: "2024-01-13",
    source: "https://attackontitan.fandom.com/wiki/Chapter_139",
  },
  {
    id: "4",
    title: "Demon Slayer",
    current_chapter: "205",
    status: "ENDED",
    img_path: "/placeholder.svg?height=400&width=300",
    rating: 8.8,
    updatedAt: "2024-01-12",
    source: "https://demonslayer.fandom.com/wiki/Chapter_205",
  },
  {
    id: "5",
    title: "Jujutsu Kaisen",
    current_chapter: "248",
    status: "ONGOING",
    img_path: "/placeholder.svg?height=400&width=300",
    rating: 9.1,
    updatedAt: "2024-01-11",
    source: "https://jujutsu-kaisen.fandom.com/wiki/Chapter_248",
  },
  {
    id: "6",
    title: "Tower of God",
    current_chapter: "612",
    status: "SEASON END",
    img_path: "/placeholder.svg?height=400&width=300",
    rating: 8.9,
    updatedAt: "2024-01-10",
    source: "https://towerofgod.fandom.com/wiki/Chapter_612",
  },
  {
    id: "7",
    title: "The Beginning After The End",
    current_chapter: "187",
    status: "ONGOING",
    img_path: "/placeholder.svg?height=400&width=300",
    rating: 9.3,
    updatedAt: "2024-01-09",
    source: "https://thebeginningaftertheend.fandom.com/wiki/Chapter_187",
  },
  {
    id: "8",
    title: "Chainsaw Man",
    current_chapter: "155",
    status: "ONGOING",
    img_path: "/placeholder.svg?height=400&width=300",
    rating: 8.7,
    updatedAt: "2024-01-08",
    source: "https://chainsaw-man.fandom.com/wiki/Chapter_155",
  },
  {
    id: "9",
    title: "Hunter x Hunter",
    current_chapter: "400",
    status: "DROPPED",
    img_path: "/placeholder.svg?height=400&width=300",
    rating: 9.4,
    updatedAt: "2023-12-20",
    source: "https://hunterxhunter.fandom.com/wiki/Chapter_400",
  },
  {
    id: "10",
    title: "My Hero Academia",
    current_chapter: "410",
    status: "SEASON END",
    img_path: "/placeholder.svg?height=400&width=300",
    rating: 8.6,
    updatedAt: "2024-01-07",
    source: "https://myheroacademia.fandom.com/wiki/Chapter_410",
  },
  {
    id: "11",
    title: "Naruto",
    current_chapter: "700",
    status: "ENDED",
    img_path: "/placeholder.svg?height=400&width=300",
    rating: 8.9,
    updatedAt: "2023-11-15",
    source: "https://naruto.fandom.com/wiki/Chapter_700",
  },
  {
    id: "12",
    title: "Bleach",
    current_chapter: "686",
    status: "ENDED",
    img_path: "/placeholder.svg?height=400&width=300",
    rating: 8.5,
    updatedAt: "2023-10-20",
    source: "https://bleach.fandom.com/wiki/Chapter_686",
  },
]
